services:

  mongodb:
    image: mongodb/mongodb-atlas-local
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./database_init:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017

  edge_manager:
    build: .
    container_name: edge_manager
    environment:
      - MONGO_URI=mongodb://user:pass@mongodb:27017/?directConnection=true
    ports:
      - 8000:8000
    depends_on:
      - mongodb
  